- hosts: apt
  remote_user: ansible
  become: true
  become_user: root
  tasks:
  - name: Update all packages
    apt:
      name: '*'
      update_cache: yes
      only_upgrade: yes
      state: latest
  - name: Remove unneeded packages
    apt:
      autoremove: yes